version: '3.8'
services:
  postgres-gorm:
    image: postgres:13
    ports:
      - '5432:5435'
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=canteen
    networks:
      - postgres-gorm-network
networks:
  postgres-gorm-network:
    driver: bridge